site_name: ModuleManager Wiki
repo_url: https://github.com/kopernicuswiki/mmwiki.git
theme: readthedocs
nav:
    - Home: 'index.md'
    - ConfigNodes: 'confignodes.md'
    - Basics:
        - 'Prefixes and Commands': 'basics/prefixes-cmds.md'
        - 'Special Characters': 'basics/specialchars.md'
        - 'Patch Ordering': 'basics/ordering.md'
        - 'Passes': 'basics/passes.md'
        - 'Targeting By Index': 'basics/targetbyindex.md'
    - Intermediate:
        - 'Variables': 'intermediate/variables'
        - 'Regex Replacement': 'intermediate/regex.md'
